[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
bevy_flycam = "0.11.0"
noise = "0.8.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
